### ISSUE TITLE
session in main thread 

### ISSUE THREAD

**Issue by shimaamorsy** [AndreyGermanov/yolov8_inference_video_javascript#3]
What about making the session of models in main thread and send it to worker ?

**Comment by AndreyGermanov** [comment]
It will not work. The session object is not serializable. Only serializable data can be transferred from one thread to another.

**Comment by shimaamorsy** [comment]
Is there any way to deserialize this object ?

**Comment by AndreyGermanov** [comment]
> Is there any way to deserialize this object ?

Unfortunately no, because before sending the object to the worker thread, the WebWorkers engine serializes it using the "structured clone" algorithm. This algorithm can serialize only objects with data, but not objects with functions, as described here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm.

Sending the session object without functions does not have any sense, because you need to execute functions to run models.

It's not clear, why do you need to create the session object in the main thread and then send it? If the model executed in the worker thread, then it should be created in that thread, as it works now.

In general, it's not a good practice to send objects. You should send data instead.

**Comment by shimaamorsy** [comment]
I have two more questions
1- Is it possible to store the session in the browser’s storage? Because when I tried, I did not know .
2- If I have a large number of images that I want to apply detection to, is there a way that I can use  to run the models on the images to speed up the process a little?

**Comment by AndreyGermanov** [comment]
> I have two more questions 

Here are some brief ideas about this, that can be used to research further:

> 1- Is it possible to store the session in the browser’s storage? Because when I tried, I did not know . 

It's not possible to save the session to browser's storage for the same reason, as it can't be transferred to the worker. However, it's possible to save the model ONNX file to the browser storage and then load this model to the session from the browser's storage.

To do this, you need to load the ONNX file to the browser as an ArrayBuffer, then save this buffer to the cache. Depending on the model size, you can select either LocalStorage, if the model is small, or IndexedDB if it's large. I think, for YOLOv8 model, you should choose the IndexedDB storage.

Finally, to use the model, stored in the browser, you need to load this array buffer from storage and pass it to the InferenceSession.create() method instead of file name.

By the way, the ArrayBuffer can be transferred from main thread to the worker thread, because it's binary data that can be serialized.

> 2- If I have a large number of images that I want to apply detection to, is there a way that I can use to run the models on the images to speed up the process a little?

The YOLOv8 supports batch inference. To use it, you need to export the model to ONNX with batch support. To do this, you need to set "dynamic=True" option when export to ONNX from Pytorch: https://docs.ultralytics.com/modes/export/#arguments. 

Then, having the ONNX model with batch support, you can pass several images to it by concatenating them one after another and transforming to the tensor of size (X,3,640,640) where X is a number of images that you want to pass to the model in a single run.

There is a second option, if you have a few images, like 2 or 3, you can just concatenate them vertically or horizontally and use it as a single image for detection. It could work faster, but the prediction quality can decrease, because this big image will be resized to 640x640.

**Comment by shimaamorsy** [comment]
Thank you very much for your help, sir
I have one last question. I want to perform detection for all the objects in the video. I will use YOLO for detection in one frame. For the next 50 subsequent frames, I intend to apply tracking on the detected objects. Since everything is in JavaScript for browser compatibility, I'm struggling to find sufficient materials on tracking multiple objects using the Camshift algorithm. If you know of any resources or websites that can assist me with this task, I would greatly appreciate your help

**Comment by shimaamorsy** [comment]
If you have suggestions for algorithms through which I can track multiple objects in javascript, can you tell me about them as well?

**Comment by shimaamorsy** [comment]
?!

**Comment by AndreyGermanov** [comment]
> Thank you very much for your help, sir I have one last question. I want to perform detection for all the objects in the video. I will use YOLO for detection in one frame. For the next 50 subsequent frames, I intend to apply tracking on the detected objects. Since everything is in JavaScript for browser compatibility, I'm struggling to find sufficient materials on tracking multiple objects using the Camshift algorithm. If you know of any resources or websites that can assist me with this task, I would greatly appreciate your help

I haven't done this in a web browser, found only this: https://www.youtube.com/watch?v=OkRMOAWlBp4, however it does not look stable now. OpenCV.js is pretty old and not well documented. That's all that I could find for now.

**Comment by AndreyGermanov** [comment]
> If you have suggestions for algorithms through which I can track multiple objects in javascript, can you tell me about them as well?

One more good object tracking algorithm is based on Kalman Filters. It has a low-level implementation on JavaScript: https://github.com/piercus/kalman-filter, however, I have not used it yet.  

I do research in this direction and going to write and publish an article about object tracking algorithms and their comparison in coming months, so you can follow me to know when it happens.

**Comment by shimaamorsy** [comment]
Thank you. I have one last question: how can I run the model (onnx format) on the GPU?
